name: overleaf-kodotiq-ojp4uc

services:
  sharelatex:
    restart: always
    image: sharelatex/sharelatex
    container_name: overleaf-kodotiq-ojp4uc-sharelatex
    depends_on:
      overleaf-mongo:
        condition: service_healthy
      overleaf-redis:
        condition: service_started
    ports:
      - 8090:80
    stop_grace_period: 60s
    volumes:
      - ~/sharelatex_data:/var/lib/overleaf
    environment:
      OVERLEAF_APP_NAME: Overleaf Community Edition
      OVERLEAF_MONGO_URL: mongodb://overleaf-mongo:27017/sharelatex?replicaSet=overleaf
      OVERLEAF_REDIS_HOST: overleaf-redis
      REDIS_HOST: overleaf-redis
      ENABLED_LINKED_FILE_TYPES: "project_file,project_output_file"
      ENABLE_CONVERSIONS: "true"
      EMAIL_CONFIRMATION_DISABLED: "true"
      OVERLEAF_SITE_URL: http://latex.kodotiq.com
      OVERLEAF_NAV_TITLE: Overleaf Community Edition
      SANDBOXED_COMPILES: "true"
      SANDBOXED_COMPILES_HOST_DIR_COMPILES: "/home/user/sharelatex_data/data/compiles"
      SANDBOXED_COMPILES_HOST_DIR_OUTPUT: "/home/user/sharelatex_data/data/output"
      DOCKER_RUNNER: "true"
      SANDBOXED_COMPILES_SIBLING_CONTAINERS: "true"
    networks:
      - dokploy-network
      - overleaf-network

  overleaf-mongo:
    restart: always
    image: mongo:8.0
    container_name: overleaf-kodotiq-ojp4uc-mongo
    command: "--replSet overleaf"
    volumes:
      - ~/overleaf_mongo_data:/data/db
      - ./bin/shared/mongodb-init-replica-set.js:/docker-entrypoint-initdb.d/mongodb-init-replica-set.js
    environment:
      MONGO_INITDB_DATABASE: sharelatex
    extra_hosts:
      - mongo:127.0.0.1
    healthcheck:
      test: echo 'db.stats().ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
    networks:
      - dokploy-network
      - overleaf-network

  overleaf-redis:
    restart: always
    image: redis:6.2
    container_name: overleaf-kodotiq-ojp4uc-redis
    volumes:
      - ~/overleaf_redis_data:/data
    networks:
      - dokploy-network
      - overleaf-network

networks:
  dokploy-network:
    external: true
  overleaf-network:
    driver: bridge
